name: Docker Image CI

on:
  create:
    tags:
    - '^(\d+\.?){1,3}$'
  schedule:
    # As well as running when we make changes we should run at least
    # every week in order to pick up new parent images
    - cron:  "0 0 * * 0"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:    
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          add_git_labels: true
          repository: ${{ secrets.DOCKER_USER }}/kubectl
          tags: ${{ github.ref }}
          buildargs: KUBECTL_VERSION=${{ github.ref }}