name: Docker Image CD on tag creation

on:
  create:
    tags:
    - '^(\d+\.?){1,3}$'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:    
      fail-fast: false
      matrix:
        image_name: [ubuntu]
        image_version: [18.04, 20.04]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          add_git_labels: true
          repository: ${{ secrets.DOCKER_USER }}/kubectl
          tags: ${{ github.ref }}-${{ matrix.image_name }}:${{ matrix.image_version }}
          build_args: KUBECTL_VERSION=${{ github.ref }}, IMAGE=${{ matrix.image_name }}:${{ matrix.image_version }}